// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DiscountEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiscountStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDiscountActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IsDiscountActive", "DiscountStart", "DiscountEnd")
                        .HasDatabaseName("Product_IsDiscountActive_DiscountStart_DiscountEnd");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest Apple smartphone with A17 Pro chip",
                            IsDiscountActive = false,
                            Name = "iPhone 15 Pro",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship Android smartphone by Samsung",
                            IsDiscountActive = false,
                            Name = "Samsung Galaxy S24",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apple laptop with M3 chip",
                            IsDiscountActive = false,
                            Name = "MacBook Pro M3",
                            Price = 2499.50m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computers",
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium Windows ultrabook laptop",
                            IsDiscountActive = false,
                            Name = "Dell XPS 15",
                            Price = 1999.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise cancelling wireless headphones",
                            IsDiscountActive = false,
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Wearables",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smart watch with health tracking",
                            IsDiscountActive = false,
                            Name = "Apple Watch Series 9",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced wireless productivity mouse",
                            IsDiscountActive = false,
                            Name = "Logitech MX Master 3S",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming keyboard with RGB lights",
                            IsDiscountActive = false,
                            Name = "Mechanical Keyboard RGB",
                            Price = 159.49m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Monitors",
                            CreatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "34 inch curved ultrawide monitor",
                            IsDiscountActive = false,
                            Name = "LG UltraWide Monitor",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic gaming chair with lumbar support",
                            IsDiscountActive = false,
                            Name = "Gaming Chair Pro",
                            Price = 349.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
